print("hello world")
dkv,sjndfv,jsfnv
SLKDDvnsljfnkguhqworug
sdkvvbaskdjhbvksujdvkbswdr
wddgvjeakhhfughbbeufhowd
wdkjhahkrudfhiuyhkrwng
swdulfhaikushfiuhworhifw
rdgliiwihrkughiqwurogfhwre
gewrlghkerudygoiwowldlshod

